[tools]
python = "latest"
node = "lts"
rust = "latest"
jq = "latest"
ripgrep = "latest"
fd = "latest"
fzf = "latest"
uv = "latest"
bat = "latest"
eza = "latest"
lazygit = "latest"
gh = "latest"
direnv = "latest"

[settings]
experimental = true
